name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Hace checkout del repositorio
      uses: actions/checkout@v3
      
      
    - name: Login en Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_TOKEN }}
        
    - name: Configura Docker Buildx
      id: buildx
      uses: docker/setup-buildx-action@v1
        
    - name: Crear y subir imagen
      id: docker_build
      uses: docker/build-push-action@v2
      with:
          context: ./
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/sql-server:latest
          
    - name: digest de la imagen
      run: echo ${{ steps.docker_build.outputs.digest }}      
   # - name: Build the Docker image
   # run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
